# Generated by Django 5.0.2 on 2024-02-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transacction_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='../media/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../media/suppliers')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('review', models.IntegerField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pivot_Products_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
                ('fk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
                ('fk_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.products')),
                ('fk_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplier')),
                ('fk_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.transaction')),
            ],
        ),
    ]
