# Generated by Django 5.0.2 on 2024-03-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_exit_fk_product_remove_exit_fk_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='fk_product',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='products',
        ),
        migrations.AddField(
            model_name='entries',
            name='product',
            field=models.ManyToManyField(to='stock.products'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='product',
            field=models.ManyToManyField(to='stock.products'),
        ),
    ]
