# Generated by Django 5.0.2 on 2024-03-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_entries_fk_product_remove_suppliers_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock.categories'),
        ),
    ]
