# Generated by Django 5.0.2 on 2024-03-21 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_products_total_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='entries',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='image',
            field=models.ImageField(upload_to='suppliers/'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='review',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
