# Generated by Django 5.0.2 on 2024-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rename_product_entries_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('entry', models.ManyToManyField(to='stock.entries')),
                ('products', models.ManyToManyField(to='stock.products')),
            ],
        ),
    ]
