# Generated by Django 5.0.2 on 2024-04-04 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entries',
            options={'verbose_name': 'Entries', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entry'},
        ),
        migrations.AlterModelOptions(
            name='exits',
            options={'verbose_name': 'Exits', 'verbose_name_plural': 'Exits'},
        ),
        migrations.RemoveField(
            model_name='entries',
            name='products',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='exits',
            name='product',
        ),
        migrations.RemoveField(
            model_name='exits',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
        migrations.AddField(
            model_name='entry',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.entries'),
        ),
        migrations.AddField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.suppliers'),
        ),
        migrations.AddField(
            model_name='exits',
            name='datetime',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default='brand', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='total_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='datetime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='total',
            field=models.IntegerField(blank=True),
        ),
        migrations.RemoveField(
            model_name='entries',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='products',
        ),
        migrations.AlterField(
            model_name='exits',
            name='total',
            field=models.IntegerField(blank=True),
        ),
        migrations.RemoveField(
            model_name='exits',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categories'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categories'),
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('exit_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.exits')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.products')),
            ],
            options={
                'verbose_name': 'Exit',
                'verbose_name_plural': 'Exit',
            },
        ),
        migrations.AddField(
            model_name='entries',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.transactions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.products'),
        ),
        migrations.AddField(
            model_name='exits',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.transactions'),
            preserve_default=False,
        ),
    ]
